### ISSUE TITLE
The trigger in the knative/deploy uses old `v1beta` API version

### ISSUE THREAD

**Issue by afrittoli** [ruromero/cloudevents-player#16]
The `cloudevents-player` is mentioned in the latest [knative docs](https://knative.dev/docs/getting-started/first-trigger/) however it won't deploy against knative v0.24.0 because the `Trigger` CRD moved to `v1` from `v1beta`.

**Comment by ruromero** [comment]
Thanks for letting me know. I have updated the `Trigger`
