### ISSUE TITLE
possible to support ARM images?

### ISSUE THREAD

**Issue by larrycai** [ruromero/cloudevents-player#23]
I try to learn it using minikube@Mac M1, but the image doesn't exist and I tried to rebuild

<pre>
$ podman build -t quay.io/ruben/cloudevents-player:latest -f src/main/docker/Dockerfile.native .
STEP 1/6: FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
Trying to pull registry.access.redhat.com/ubi8/ubi-minimal:8.3...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:56a04d997355c19a50990df9442628967dba3293799b2c058e9e6feae7c00e91
Copying blob sha256:9f2d1a2655b9b1c4e7a454a14b61d91972c2d9c6b5936eca839a994cf6483017
Copying config sha256:161b5eee3a1af34f1f9432ca11debf7abef432824a12418508256c38d1de18fa
Writing manifest to image destination
Storing signatures
STEP 2/6: WORKDIR /work/
--> 0db0961f608
STEP 3/6: COPY target/*-runner /work/application
Error: building at STEP "COPY target/*-runner /work/application": checking on sources under "/var/tmp/libpod_builder2131162895/build": Rel: can't make  relative to /var/tmp/libpod_builder2131162895/build; copier: stat: ["/target/*-runner"]: no such file or directory
</pre>

Possible to provide arm image or fix dockerfile for it?

**Comment by ruromero** [comment]
Hey @larrycai 
The error is telling you that the target/cloudevent-player-1.1-SNAPSHOT-runner file does not exist. You could run the `mvn clean install -Pcontainer` that generates the native binary and then it runs the docker/podman build locally.

the ubi-minimal:8.3 image is multi-arch and you should be able to build your arm64 image locally with this same command.

If you don't want to do the build locally, you can try the multi-stage build that I have provided in PR #22 (but I haven't tested it properly)

**Comment by larrycai** [comment]
I thought the build was inside the container build as well (I haven't touched java for a while)

tried below 

````
$ brew install maven
$ mvn clean install -Pnative
...
[INFO] Finished at: 2022-12-20T13:43:38+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.1.Final:build (default) on project cloudevent-player: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Cannot find the `native-image` in the GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image`
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.getNativeImageBuildRunner(NativeImageBuildStep.java:260)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:155)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1589)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
````

Maybe it is simple to fix by java developers, but not me now ;-)

**Comment by ruromero** [comment]
I have fixed an issue with the integrationTests and I've also created a GitHub action to perform a multi-arch build. You can check `quay.io/ruben/cloudevents-player:v1.2`
